version: '3.8'

name: winwin-travel

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: winwin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  auth-api:
    build: ./auth-api
    container_name: auth-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - data-api
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/winwin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      JWT_SECRET: winwin-travel-super-secret-jwt-key
      INTERNAL_TOKEN: my-internal-token

      DATA_API_URL: http://data-api:8081

  data-api:
    build: ./data-api
    container_name: data-api
    ports:
      - "8081:8081"
    environment:
      INTERNAL_TOKEN: my-internal-token