spring:
  application:
    name: auth-api

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5434/winwin}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

data:
  api:
    url: ${DATA_API_URL:http://localhost:8081}

internal:
  token: ${INTERNAL_TOKEN:my-internal-token}

jwt:
  secret: ${JWT_SECRET:winwin-travel-super-secret-jwt-key}